substitutions:
  # main prefix for all entities
  name: "Thermotronic Smart"
  # name of your node
  node_name: "thermotronic-smart"
  # add suffix for node name to have one firmware for many devices.
  node_add_mac_suffix: "false"
  # use "esp12e" for iot-uni-dongle, "esp8285" for coolrf-heatstick, or your own if you know it
  # board: "esp01_1m"
  board: "esp01_1m"
  # SSID of your wifi
  wifi_ssid: !secret wifi_ssid
  # password of your wifi
  wifi_password: !secret wifi_password
  # password for fallback wifi hotspot
  wifi_ap_password: !secret wifi_ap_password
  # version of ewh
  project_version: "2022.11.0"

external_components:
  - source: components

# please do not change packeages order it is very important, just comment/uncomment
packages:
  ## optional package, uncomment next line to enable standalone web ui
  # web: github://dentra/esphome-ewh/packages/ets_web.yaml@$project_version
  web: !include packages/ets_web.yaml

  wifi_signal: !include packages/wifi_signal.yaml
  restart: !include packages/restart.yaml
  uptime: !include packages/uptime.yaml

  debug: !include packages/debug.yaml

  platform: !include packages/esp8266.yaml
  # required package, do not comment
  #common: github://dentra/esphome-ewh/packages/core.yaml@$project_version
  common: !include packages/common.yaml

api:

wifi:
  ssid: $wifi_ssid
  password: $wifi_password

logger:
  # Make sure logging is not using the serial port
  baud_rate: 0

# Configure hardware serial port
uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600

# Configure virtual port
vport:
  - platform: ets

# Configure API
ets:
  on_state:
    then:
      lambda: |-
        // do some stuff

# Configure climate component
climate:
  - platform: ets
    name: None # use friendly_name
    floor_temperature:
      name: "$name Floor Temperature"

# Configure cloud support
rka_cloud:
  id: cloud
  name: "Cloud"
  pair:
    name: "Pair"
  mac: !secret cloud_mac_ets
  # uid: !secret cloud_uid_ets

button:
  - platform: factory_reset
    name: "Factory Reset"
