# !!!
# !!! This file is for development purpose only !!!
# !!!
substitutions:
  # main prefix for all entities
  name: "Water Heater"
  # name of your node
  node_name: "water-heater"
  # use "esp12e" for iot-uni-dongle, "esp8285" for coolrf-heatstick
  board: "esp12e"
  # time platform: "sntp" or "homeassistant"
  time_platform: "homeassistant"
  # SSID of your wifi
  wifi_ssid: !secret wifi_ssid
  # password of your wifi
  wifi_password: !secret wifi_password
  # password for fallback wifi hotspot
  wifi_ap_password: !secret wifi_ap_password
  # version of ewh
  ewh_version: "master"

packages:
  ewh: !include packages/ewh.yaml
  clock: !include packages/clock.yaml
  timer: !include packages/timer.yaml
  web: !include packages/web.yaml # must follow before core and after ewh
  cloud: !include packages/cloud.yaml # must follow before core
  core: !include packages/core.yaml

external_components:
  - source: components

time:
  platform: $time_platform
  timezone: UTC-3

ewh_cloud:
  mac: !secret cloud_mac
  uid: !secret cloud_uid

