logger:
  level: VERBOSE
  logs:
    ota: DEBUG
    mdns: INFO
    wifi: INFO
    sntp: INFO
    esp-idf: INFO
    api.connection: INFO
    api: INFO
    button: INFO
    switch: INFO
    sensor: INFO
    select: INFO
    number: INFO
    climate: DEBUG
    text_sensor: INFO
    binary_sensor: INFO
    esp32_ble_tracker: INFO
    json: INFO
    uptime.sensor: INFO
    wifi_signal.sensor: INFO

debug:
  update_interval: 5s

sensor:
  - platform: debug
    free:
      name: "Min Heap Free"
      filters:
        - lambda: |-
            static size_t min = 0xFFFFFFFF;
            if (x < min) {
              min = x;
            }
            return min;
    loop_time:
      name: "Loop Time"
