substitutions:
  board: esp32-s3-devkitc-1
  framework_type: esp-idf

esphome:
  platformio_options:
    board_build.flash_mode: dio
    build_flags:
      - -std=gnu++17
    build_unflags:
      - -std=gnu++11
    lib_ldf_mode: "chain" # required for ESP32 AsyncUDP library search

esp32:
  board: $board
  framework:
    type: $framework_type

esp32_usb_dis:
